//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data
    {
        public int id { get; set; }
        public string name { get; set; }
        public string applicationDateAndTime { get; set; }
        public string dateAndTimeOfCarProvision { get; set; }
        public string purposesOfUsingAuto { get; set; }
        public string route { get; set; }
        public string nameDocument { get; set; }
        public int id_employe { get; set; }
        public string cargo { get; set; }
        public Nullable<int> id_driver { get; set; }
        public string applicationStatus { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
