//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public Employees()
        {
            this.Data = new HashSet<Data>();
        }
    
        public int id { get; set; }
        public string fullName { get; set; }
        public string password { get; set; }
        public bool accessRights { get; set; }
        public string login { get; set; }
    
        public virtual ICollection<Data> Data { get; set; }
    }
}
